name: 'Repository Cleaner'
description: 'Deletes all branches, tags, release, and history for a nice and clean repository'
author: "Thor Lyster Lind"
inputs:
  gh-token:
    description: 'Github Token'
    required: true
  init-message:
    description: 'The commit which all files will be set to, defaults to `Init Commit`'
    required: false
    default: 'Init Commit'
  wipe-deployments:
    description: 'defaults to `true`'
    required: false
    default: 'true'
  wipe-workflow-history:
    description: 'defaults to `true`'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Clean repo
      run: cleaner.sh "${{ github.repository }}" "${{ inputs.init-message }}" "${{ github.actor }}" "${{ inputs.wipe-deployments }}" "${{ inputs.wipe-workflow-history }}" ${{ github.run_id}}
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}


branding:
  icon: alert-triangle
  color: red
